version: '3.3'

services:
  rtmp:
    image: tiangolo/nginx-rtmp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 1936
      published: 1936
      protocol: tcp
    - target: 8080
      published: 8080
      protocol: tcp
    dns:
      - 1.1.1.1
      - 8.8.8.8
    network_mode: "bridge"
    links:
    - stunnel
  stunnel:
    build: stunnel
    network_mode: "bridge"
